# request definition
nav_msgs/Path path
---
# response definition
uint16 SUCCESS=0
uint16 FAILURE=1
uint16 OBSTACLE_DETECTED=2

std_msgs/Empty result
uint16 error_code
---
# feedback definition
float32 distance_to_goal
