twist_mux:
  ros__parameters:
    topics:
      autonomous_navigation:
        topic: /cmd_vel_autonomous
        timeout: 10.0
        priority: 1
      teleoperation:
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 3

    locks:
      autonomous_navigation:
        topic: /autonomous_disabled
        timeout: 0.0
        priority: 2
      e_stop:
        topic: /e_stop
        timeout: 0.0
        priority: 255
