/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "urc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ArmEncodersMessage, ArmEncodersMessage, AUTO)


PB_BIND(DrivetrainRequest, DrivetrainRequest, AUTO)


PB_BIND(NewStatusLightCommand, NewStatusLightCommand, AUTO)


PB_BIND(TeensyMessage, TeensyMessage, AUTO)


PB_BIND(RequestMessage, RequestMessage, AUTO)


PB_BIND(IMUMessage, IMUMessage, AUTO)


PB_BIND(BatteryMessage, BatteryMessage, AUTO)


PB_BIND(StatusLightCommand, StatusLightCommand, AUTO)


PB_BIND(ScienceModuleCommand, ScienceModuleCommand, AUTO)


PB_BIND(DriveCurrentRequest, DriveCurrentRequest, AUTO)


PB_BIND(StatusLightRequest, StatusLightRequest, AUTO)


PB_BIND(ArmPositionRequest, ArmPositionRequest, AUTO)


PB_BIND(ArmClawRequest, ArmClawRequest, AUTO)


PB_BIND(DriveFeedback, DriveFeedback, AUTO)


PB_BIND(ArmFeedback, ArmFeedback, AUTO)



