/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_URC_PB_H_INCLUDED
#define PB_URC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ArmClawRequest { 
    bool has_clawVel;
    int32_t clawVel;
} ArmClawRequest;

typedef struct _ArmEffortRequest { 
    bool has_shoulderLiftEffort;
    int32_t shoulderLiftEffort;
    bool has_shoulderSwivelEffort;
    int32_t shoulderSwivelEffort;
    bool has_elbowLiftEffort;
    int32_t elbowLiftEffort;
    bool has_wristLiftEffort;
    int32_t wristLiftEffort;
    bool has_wristSwivelEffort;
    int32_t wristSwivelEffort;
    bool has_clawVel;
    int32_t clawVel;
} ArmEffortRequest;

/* Reports the encoder ticks for each arm joint */
typedef struct _ArmEncodersMessage { 
    int32_t shoulderLiftTicks;
    int32_t shouldSwivelTicks;
    int32_t elbowLiftTicks;
    int32_t elbowSwivelTicks;
    int32_t wristLiftTicks;
    int32_t wristSwivelTicks;
} ArmEncodersMessage;

typedef struct _ArmPositionFeedback { 
    bool has_shoulderLiftTicks;
    int32_t shoulderLiftTicks;
    bool has_shoulderSwivelTicks;
    int32_t shoulderSwivelTicks;
    bool has_elbowLiftTicks;
    int32_t elbowLiftTicks;
    bool has_wristLiftTicks;
    int32_t wristLiftTicks;
    bool has_wristSwivelTicks;
    int32_t wristSwivelTicks;
} ArmPositionFeedback;

typedef struct _BatteryMessage { 
    /* cell voltages */
    bool has_mainVoltage;
    float mainVoltage;
    bool has_cell1Voltage;
    float cell1Voltage;
    bool has_cell2Voltage;
    float cell2Voltage;
    bool has_cell3Voltage;
    float cell3Voltage;
    bool has_cell4Voltage;
    float cell4Voltage;
    bool has_cell5Voltage;
    float cell5Voltage;
    bool has_cell6Voltage;
    float cell6Voltage;
    bool has_cell7Voltage;
    float cell7Voltage;
    bool has_cell8Voltage;
    float cell8Voltage;
    /* charge state */
    bool has_chargePercentage;
    float chargePercentage;
    /* discharge state */
    bool has_dischargeCurrent;
    float dischargeCurrent;
} BatteryMessage;

typedef struct _DriveEncodersMessage { 
    bool has_leftSpeed;
    int32_t leftSpeed;
    bool has_rightSpeed;
    int32_t rightSpeed;
    int32_t timestamp;
} DriveEncodersMessage;

typedef struct _DrivetrainRequest { 
    int32_t m1Setpoint;
    int32_t m2Setpoint;
    int32_t m3Setpoint;
    int32_t m4Setpoint;
} DrivetrainRequest;

typedef struct _DrivetrainResponse { 
    int32_t m1SpeedFeedback;
    uint32_t m1Current;
    int32_t m1PositionFeedback;
    int32_t m2SpeedFeedback;
    uint32_t m2Current;
    int32_t m2PositionFeedback;
    int32_t m3SpeedFeedback;
    uint32_t m3Current;
    int32_t m3PositionFeedback;
    int32_t m4SpeedFeedback;
    uint32_t m4Current;
    int32_t m4PositionFeedback;
} DrivetrainResponse;

typedef struct _IMUMessage { 
    int32_t timestamp;
    bool has_quaternionX;
    float quaternionX;
    bool has_quaternionY;
    float quaternionY;
    bool has_quaternionZ;
    float quaternionZ;
    bool has_quaternionW;
    float quaternionW;
    bool has_linearAccelX;
    float linearAccelX;
    bool has_linearAccelY;
    float linearAccelY;
    bool has_linearAccelZ;
    float linearAccelZ;
    bool has_angularVelocityX;
    float angularVelocityX;
    bool has_angularVelocityY;
    float angularVelocityY;
    bool has_angularVelocityZ;
    float angularVelocityZ;
} IMUMessage;

typedef struct _NewStatusLightCommand { 
    int32_t redEnabled;
    int32_t blueEnabled;
    int32_t greenEnabled;
    int32_t redBlink;
    int32_t blueBlink;
    int32_t greenBlink;
} NewStatusLightCommand;

typedef struct _RequestMessage { 
    bool requestSpeed;
    bool requestDiagnostics;
    bool has_leftSpeed;
    int32_t leftSpeed;
    bool has_rightSpeed;
    int32_t rightSpeed;
    bool has_duration;
    int32_t duration;
    int32_t timestamp;
} RequestMessage;

typedef struct _ScienceModuleCommand { 
    int32_t rotateTurntable;
} ScienceModuleCommand;

typedef struct _ScienceMotorRequest { 
    bool has_leadscrewVel;
    int32_t leadscrewVel;
    bool has_turntableVel;
    int32_t turntableVel;
    bool has_drillEffort;
    int32_t drillEffort;
} ScienceMotorRequest;

typedef struct _SetpointMessage { 
    int32_t leftSetpoint;
    int32_t rightSetpoint; /* required int32 m1Setpoint = 1;
required int32 m2Setpoint = 2;
required int32 m3Setpoint = 3;
required int32 m4Setpoint = 4;
required int32 m5Setpoint = 5;
required int32 m6Setpoint = 6; */
} SetpointMessage;

typedef struct _StatusLightCommand { 
    bool has_color;
    int32_t color;
    bool has_display;
    int32_t display;
} StatusLightCommand;

typedef struct _StatusLightMessage { 
    /* required int32 lightCommand = 1; */
    int32_t redEnabled;
    int32_t blueEnabled;
    int32_t greenEnabled;
    int32_t redBlink;
    int32_t blueBlink;
    int32_t greenBlink;
} StatusLightMessage;

typedef struct _TeensyMessage { 
    pb_size_t which_messageType;
    union {
        StatusLightMessage statusLightMessage;
        SetpointMessage setpointMessage;
    } messageType;
} TeensyMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ArmEncodersMessage_init_default          {0, 0, 0, 0, 0, 0}
#define DriveEncodersMessage_init_default        {false, 0, false, 0, 0}
#define DrivetrainRequest_init_default           {0, 0, 0, 0}
#define DrivetrainResponse_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RequestMessage_init_default              {0, 0, false, 0, false, 0, false, 0, 0}
#define StatusLightCommand_init_default          {false, 0, false, 0}
#define NewStatusLightCommand_init_default       {0, 0, 0, 0, 0, 0}
#define StatusLightMessage_init_default          {0, 0, 0, 0, 0, 0}
#define SetpointMessage_init_default             {0, 0}
#define BatteryMessage_init_default              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define IMUMessage_init_default                  {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ScienceModuleCommand_init_default        {0}
#define TeensyMessage_init_default               {0, {StatusLightMessage_init_default}}
#define ArmClawRequest_init_default              {false, 0}
#define ArmEffortRequest_init_default            {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ArmPositionFeedback_init_default         {false, 0, false, 0, false, 0, false, 0, false, 0}
#define ScienceMotorRequest_init_default         {false, 0, false, 0, false, 0}
#define ArmEncodersMessage_init_zero             {0, 0, 0, 0, 0, 0}
#define DriveEncodersMessage_init_zero           {false, 0, false, 0, 0}
#define DrivetrainRequest_init_zero              {0, 0, 0, 0}
#define DrivetrainResponse_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RequestMessage_init_zero                 {0, 0, false, 0, false, 0, false, 0, 0}
#define StatusLightCommand_init_zero             {false, 0, false, 0}
#define NewStatusLightCommand_init_zero          {0, 0, 0, 0, 0, 0}
#define StatusLightMessage_init_zero             {0, 0, 0, 0, 0, 0}
#define SetpointMessage_init_zero                {0, 0}
#define BatteryMessage_init_zero                 {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define IMUMessage_init_zero                     {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ScienceModuleCommand_init_zero           {0}
#define TeensyMessage_init_zero                  {0, {StatusLightMessage_init_zero}}
#define ArmClawRequest_init_zero                 {false, 0}
#define ArmEffortRequest_init_zero               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ArmPositionFeedback_init_zero            {false, 0, false, 0, false, 0, false, 0, false, 0}
#define ScienceMotorRequest_init_zero            {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ArmClawRequest_clawVel_tag               1
#define ArmEffortRequest_shoulderLiftEffort_tag  1
#define ArmEffortRequest_shoulderSwivelEffort_tag 2
#define ArmEffortRequest_elbowLiftEffort_tag     3
#define ArmEffortRequest_wristLiftEffort_tag     4
#define ArmEffortRequest_wristSwivelEffort_tag   5
#define ArmEffortRequest_clawVel_tag             6
#define ArmEncodersMessage_shoulderLiftTicks_tag 1
#define ArmEncodersMessage_shouldSwivelTicks_tag 2
#define ArmEncodersMessage_elbowLiftTicks_tag    3
#define ArmEncodersMessage_elbowSwivelTicks_tag  4
#define ArmEncodersMessage_wristLiftTicks_tag    5
#define ArmEncodersMessage_wristSwivelTicks_tag  6
#define ArmPositionFeedback_shoulderLiftTicks_tag 1
#define ArmPositionFeedback_shoulderSwivelTicks_tag 2
#define ArmPositionFeedback_elbowLiftTicks_tag   3
#define ArmPositionFeedback_wristLiftTicks_tag   4
#define ArmPositionFeedback_wristSwivelTicks_tag 5
#define BatteryMessage_mainVoltage_tag           1
#define BatteryMessage_cell1Voltage_tag          2
#define BatteryMessage_cell2Voltage_tag          3
#define BatteryMessage_cell3Voltage_tag          4
#define BatteryMessage_cell4Voltage_tag          5
#define BatteryMessage_cell5Voltage_tag          6
#define BatteryMessage_cell6Voltage_tag          7
#define BatteryMessage_cell7Voltage_tag          8
#define BatteryMessage_cell8Voltage_tag          9
#define BatteryMessage_chargePercentage_tag      10
#define BatteryMessage_dischargeCurrent_tag      11
#define DriveEncodersMessage_leftSpeed_tag       1
#define DriveEncodersMessage_rightSpeed_tag      2
#define DriveEncodersMessage_timestamp_tag       3
#define DrivetrainRequest_m1Setpoint_tag         1
#define DrivetrainRequest_m2Setpoint_tag         2
#define DrivetrainRequest_m3Setpoint_tag         3
#define DrivetrainRequest_m4Setpoint_tag         4
#define DrivetrainResponse_m1SpeedFeedback_tag   1
#define DrivetrainResponse_m1Current_tag         2
#define DrivetrainResponse_m1PositionFeedback_tag 3
#define DrivetrainResponse_m2SpeedFeedback_tag   4
#define DrivetrainResponse_m2Current_tag         5
#define DrivetrainResponse_m2PositionFeedback_tag 6
#define DrivetrainResponse_m3SpeedFeedback_tag   7
#define DrivetrainResponse_m3Current_tag         8
#define DrivetrainResponse_m3PositionFeedback_tag 9
#define DrivetrainResponse_m4SpeedFeedback_tag   10
#define DrivetrainResponse_m4Current_tag         11
#define DrivetrainResponse_m4PositionFeedback_tag 12
#define IMUMessage_timestamp_tag                 1
#define IMUMessage_quaternionX_tag               2
#define IMUMessage_quaternionY_tag               3
#define IMUMessage_quaternionZ_tag               4
#define IMUMessage_quaternionW_tag               5
#define IMUMessage_linearAccelX_tag              6
#define IMUMessage_linearAccelY_tag              7
#define IMUMessage_linearAccelZ_tag              8
#define IMUMessage_angularVelocityX_tag          9
#define IMUMessage_angularVelocityY_tag          10
#define IMUMessage_angularVelocityZ_tag          11
#define NewStatusLightCommand_redEnabled_tag     1
#define NewStatusLightCommand_blueEnabled_tag    2
#define NewStatusLightCommand_greenEnabled_tag   3
#define NewStatusLightCommand_redBlink_tag       4
#define NewStatusLightCommand_blueBlink_tag      5
#define NewStatusLightCommand_greenBlink_tag     6
#define RequestMessage_requestSpeed_tag          1
#define RequestMessage_requestDiagnostics_tag    2
#define RequestMessage_leftSpeed_tag             3
#define RequestMessage_rightSpeed_tag            4
#define RequestMessage_duration_tag              5
#define RequestMessage_timestamp_tag             6
#define ScienceModuleCommand_rotateTurntable_tag 1
#define ScienceMotorRequest_leadscrewVel_tag     1
#define ScienceMotorRequest_turntableVel_tag     2
#define ScienceMotorRequest_drillEffort_tag      3
#define SetpointMessage_leftSetpoint_tag         1
#define SetpointMessage_rightSetpoint_tag        2
#define StatusLightCommand_color_tag             1
#define StatusLightCommand_display_tag           2
#define StatusLightMessage_redEnabled_tag        1
#define StatusLightMessage_blueEnabled_tag       2
#define StatusLightMessage_greenEnabled_tag      3
#define StatusLightMessage_redBlink_tag          4
#define StatusLightMessage_blueBlink_tag         5
#define StatusLightMessage_greenBlink_tag        6
#define TeensyMessage_statusLightMessage_tag     1
#define TeensyMessage_setpointMessage_tag        2

/* Struct field encoding specification for nanopb */
#define ArmEncodersMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    shoulderLiftTicks,   1) \
X(a, STATIC,   REQUIRED, INT32,    shouldSwivelTicks,   2) \
X(a, STATIC,   REQUIRED, INT32,    elbowLiftTicks,    3) \
X(a, STATIC,   REQUIRED, INT32,    elbowSwivelTicks,   4) \
X(a, STATIC,   REQUIRED, INT32,    wristLiftTicks,    5) \
X(a, STATIC,   REQUIRED, INT32,    wristSwivelTicks,   6)
#define ArmEncodersMessage_CALLBACK NULL
#define ArmEncodersMessage_DEFAULT NULL

#define DriveEncodersMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    leftSpeed,         1) \
X(a, STATIC,   OPTIONAL, INT32,    rightSpeed,        2) \
X(a, STATIC,   REQUIRED, INT32,    timestamp,         3)
#define DriveEncodersMessage_CALLBACK NULL
#define DriveEncodersMessage_DEFAULT NULL

#define DrivetrainRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    m1Setpoint,        1) \
X(a, STATIC,   REQUIRED, INT32,    m2Setpoint,        2) \
X(a, STATIC,   REQUIRED, INT32,    m3Setpoint,        3) \
X(a, STATIC,   REQUIRED, INT32,    m4Setpoint,        4)
#define DrivetrainRequest_CALLBACK NULL
#define DrivetrainRequest_DEFAULT NULL

#define DrivetrainResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    m1SpeedFeedback,   1) \
X(a, STATIC,   REQUIRED, UINT32,   m1Current,         2) \
X(a, STATIC,   REQUIRED, INT32,    m1PositionFeedback,   3) \
X(a, STATIC,   REQUIRED, INT32,    m2SpeedFeedback,   4) \
X(a, STATIC,   REQUIRED, UINT32,   m2Current,         5) \
X(a, STATIC,   REQUIRED, INT32,    m2PositionFeedback,   6) \
X(a, STATIC,   REQUIRED, INT32,    m3SpeedFeedback,   7) \
X(a, STATIC,   REQUIRED, UINT32,   m3Current,         8) \
X(a, STATIC,   REQUIRED, INT32,    m3PositionFeedback,   9) \
X(a, STATIC,   REQUIRED, INT32,    m4SpeedFeedback,  10) \
X(a, STATIC,   REQUIRED, UINT32,   m4Current,        11) \
X(a, STATIC,   REQUIRED, INT32,    m4PositionFeedback,  12)
#define DrivetrainResponse_CALLBACK NULL
#define DrivetrainResponse_DEFAULT NULL

#define RequestMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     requestSpeed,      1) \
X(a, STATIC,   REQUIRED, BOOL,     requestDiagnostics,   2) \
X(a, STATIC,   OPTIONAL, INT32,    leftSpeed,         3) \
X(a, STATIC,   OPTIONAL, INT32,    rightSpeed,        4) \
X(a, STATIC,   OPTIONAL, INT32,    duration,          5) \
X(a, STATIC,   REQUIRED, INT32,    timestamp,         6)
#define RequestMessage_CALLBACK NULL
#define RequestMessage_DEFAULT NULL

#define StatusLightCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    color,             1) \
X(a, STATIC,   OPTIONAL, INT32,    display,           2)
#define StatusLightCommand_CALLBACK NULL
#define StatusLightCommand_DEFAULT NULL

#define NewStatusLightCommand_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    redEnabled,        1) \
X(a, STATIC,   REQUIRED, INT32,    blueEnabled,       2) \
X(a, STATIC,   REQUIRED, INT32,    greenEnabled,      3) \
X(a, STATIC,   REQUIRED, INT32,    redBlink,          4) \
X(a, STATIC,   REQUIRED, INT32,    blueBlink,         5) \
X(a, STATIC,   REQUIRED, INT32,    greenBlink,        6)
#define NewStatusLightCommand_CALLBACK NULL
#define NewStatusLightCommand_DEFAULT NULL

#define StatusLightMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    redEnabled,        1) \
X(a, STATIC,   REQUIRED, INT32,    blueEnabled,       2) \
X(a, STATIC,   REQUIRED, INT32,    greenEnabled,      3) \
X(a, STATIC,   REQUIRED, INT32,    redBlink,          4) \
X(a, STATIC,   REQUIRED, INT32,    blueBlink,         5) \
X(a, STATIC,   REQUIRED, INT32,    greenBlink,        6)
#define StatusLightMessage_CALLBACK NULL
#define StatusLightMessage_DEFAULT NULL

#define SetpointMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    leftSetpoint,      1) \
X(a, STATIC,   REQUIRED, INT32,    rightSetpoint,     2)
#define SetpointMessage_CALLBACK NULL
#define SetpointMessage_DEFAULT NULL

#define BatteryMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    mainVoltage,       1) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell1Voltage,      2) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell2Voltage,      3) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell3Voltage,      4) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell4Voltage,      5) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell5Voltage,      6) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell6Voltage,      7) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell7Voltage,      8) \
X(a, STATIC,   OPTIONAL, FLOAT,    cell8Voltage,      9) \
X(a, STATIC,   OPTIONAL, FLOAT,    chargePercentage,  10) \
X(a, STATIC,   OPTIONAL, FLOAT,    dischargeCurrent,  11)
#define BatteryMessage_CALLBACK NULL
#define BatteryMessage_DEFAULT NULL

#define IMUMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, FLOAT,    quaternionX,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    quaternionY,       3) \
X(a, STATIC,   OPTIONAL, FLOAT,    quaternionZ,       4) \
X(a, STATIC,   OPTIONAL, FLOAT,    quaternionW,       5) \
X(a, STATIC,   OPTIONAL, FLOAT,    linearAccelX,      6) \
X(a, STATIC,   OPTIONAL, FLOAT,    linearAccelY,      7) \
X(a, STATIC,   OPTIONAL, FLOAT,    linearAccelZ,      8) \
X(a, STATIC,   OPTIONAL, FLOAT,    angularVelocityX,   9) \
X(a, STATIC,   OPTIONAL, FLOAT,    angularVelocityY,  10) \
X(a, STATIC,   OPTIONAL, FLOAT,    angularVelocityZ,  11)
#define IMUMessage_CALLBACK NULL
#define IMUMessage_DEFAULT NULL

#define ScienceModuleCommand_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    rotateTurntable,   1)
#define ScienceModuleCommand_CALLBACK NULL
#define ScienceModuleCommand_DEFAULT NULL

#define TeensyMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (messageType,statusLightMessage,messageType.statusLightMessage),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (messageType,setpointMessage,messageType.setpointMessage),   2)
#define TeensyMessage_CALLBACK NULL
#define TeensyMessage_DEFAULT NULL
#define TeensyMessage_messageType_statusLightMessage_MSGTYPE StatusLightMessage
#define TeensyMessage_messageType_setpointMessage_MSGTYPE SetpointMessage

#define ArmClawRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    clawVel,           1)
#define ArmClawRequest_CALLBACK NULL
#define ArmClawRequest_DEFAULT NULL

#define ArmEffortRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    shoulderLiftEffort,   1) \
X(a, STATIC,   OPTIONAL, INT32,    shoulderSwivelEffort,   2) \
X(a, STATIC,   OPTIONAL, INT32,    elbowLiftEffort,   3) \
X(a, STATIC,   OPTIONAL, INT32,    wristLiftEffort,   4) \
X(a, STATIC,   OPTIONAL, INT32,    wristSwivelEffort,   5) \
X(a, STATIC,   OPTIONAL, INT32,    clawVel,           6)
#define ArmEffortRequest_CALLBACK NULL
#define ArmEffortRequest_DEFAULT NULL

#define ArmPositionFeedback_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    shoulderLiftTicks,   1) \
X(a, STATIC,   OPTIONAL, INT32,    shoulderSwivelTicks,   2) \
X(a, STATIC,   OPTIONAL, INT32,    elbowLiftTicks,    3) \
X(a, STATIC,   OPTIONAL, INT32,    wristLiftTicks,    4) \
X(a, STATIC,   OPTIONAL, INT32,    wristSwivelTicks,   5)
#define ArmPositionFeedback_CALLBACK NULL
#define ArmPositionFeedback_DEFAULT NULL

#define ScienceMotorRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    leadscrewVel,      1) \
X(a, STATIC,   OPTIONAL, INT32,    turntableVel,      2) \
X(a, STATIC,   OPTIONAL, INT32,    drillEffort,       3)
#define ScienceMotorRequest_CALLBACK NULL
#define ScienceMotorRequest_DEFAULT NULL

extern const pb_msgdesc_t ArmEncodersMessage_msg;
extern const pb_msgdesc_t DriveEncodersMessage_msg;
extern const pb_msgdesc_t DrivetrainRequest_msg;
extern const pb_msgdesc_t DrivetrainResponse_msg;
extern const pb_msgdesc_t RequestMessage_msg;
extern const pb_msgdesc_t StatusLightCommand_msg;
extern const pb_msgdesc_t NewStatusLightCommand_msg;
extern const pb_msgdesc_t StatusLightMessage_msg;
extern const pb_msgdesc_t SetpointMessage_msg;
extern const pb_msgdesc_t BatteryMessage_msg;
extern const pb_msgdesc_t IMUMessage_msg;
extern const pb_msgdesc_t ScienceModuleCommand_msg;
extern const pb_msgdesc_t TeensyMessage_msg;
extern const pb_msgdesc_t ArmClawRequest_msg;
extern const pb_msgdesc_t ArmEffortRequest_msg;
extern const pb_msgdesc_t ArmPositionFeedback_msg;
extern const pb_msgdesc_t ScienceMotorRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ArmEncodersMessage_fields &ArmEncodersMessage_msg
#define DriveEncodersMessage_fields &DriveEncodersMessage_msg
#define DrivetrainRequest_fields &DrivetrainRequest_msg
#define DrivetrainResponse_fields &DrivetrainResponse_msg
#define RequestMessage_fields &RequestMessage_msg
#define StatusLightCommand_fields &StatusLightCommand_msg
#define NewStatusLightCommand_fields &NewStatusLightCommand_msg
#define StatusLightMessage_fields &StatusLightMessage_msg
#define SetpointMessage_fields &SetpointMessage_msg
#define BatteryMessage_fields &BatteryMessage_msg
#define IMUMessage_fields &IMUMessage_msg
#define ScienceModuleCommand_fields &ScienceModuleCommand_msg
#define TeensyMessage_fields &TeensyMessage_msg
#define ArmClawRequest_fields &ArmClawRequest_msg
#define ArmEffortRequest_fields &ArmEffortRequest_msg
#define ArmPositionFeedback_fields &ArmPositionFeedback_msg
#define ScienceMotorRequest_fields &ScienceMotorRequest_msg

/* Maximum encoded size of messages (where known) */
#define ArmClawRequest_size                      11
#define ArmEffortRequest_size                    66
#define ArmEncodersMessage_size                  66
#define ArmPositionFeedback_size                 55
#define BatteryMessage_size                      55
#define DriveEncodersMessage_size                33
#define DrivetrainRequest_size                   44
#define DrivetrainResponse_size                  112
#define IMUMessage_size                          61
#define NewStatusLightCommand_size               66
#define RequestMessage_size                      48
#define ScienceModuleCommand_size                11
#define ScienceMotorRequest_size                 33
#define SetpointMessage_size                     22
#define StatusLightCommand_size                  22
#define StatusLightMessage_size                  66
#define TeensyMessage_size                       68

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
