# request definition
nav_msgs/Path path
uint16 goal_type
---
# response definition
uint16 SUCCESS=0
uint16 FAILURE=1
uint16 OBSTACLE_DETECTED=2

uint16 error_code
geometry_msgs/Pose result
---
# feedback definition
float32 distance_to_goal