# request definition
nav_msgs/Path path
uint16 GPS=0
uint16 ARUCO=1
uint16 MALLET=2
uint16 WATER_BOTTLE=3
uint16 goal_type
---
# response definition
uint16 SUCCESS=0
uint16 FAILURE=1
uint16 OBSTACLE_DETECTED=2

uint16 error_code
geometry_msgs/Pose final_goal_pose
---
# feedback definition
float32 distance_to_goal
