set(_AMENT_PACKAGE_NAME "urc_nanopb")
set(urc_nanopb_VERSION "0.0.0")
set(urc_nanopb_MAINTAINER "a-stickan <aidan.stickan@gmail.com>")
set(urc_nanopb_BUILD_DEPENDS "protobuf-dev" "python3-protobuf")
set(urc_nanopb_BUILDTOOL_DEPENDS "ament_cmake")
set(urc_nanopb_BUILD_EXPORT_DEPENDS "protobuf-dev" "python3-protobuf")
set(urc_nanopb_BUILDTOOL_EXPORT_DEPENDS )
set(urc_nanopb_EXEC_DEPENDS "protobuf-dev" "python3-protobuf")
set(urc_nanopb_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(urc_nanopb_GROUP_DEPENDS )
set(urc_nanopb_MEMBER_OF_GROUPS )
set(urc_nanopb_DEPRECATED "")
set(urc_nanopb_EXPORT_TAGS)
list(APPEND urc_nanopb_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
